name: Build and Deploy to gh-pages (avoid deprecated upload-artifact)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  # Your custom domain
  CUSTOM_DOMAIN: "www.down7x.com"

# IMPORTANT: grant 'contents: write' so the action can push the gh-pages branch
permissions:
  contents: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # fetch full history to avoid issues when creating/updating branches
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (set base automatically)
        run: |
          repo=$(echo "${GITHUB_REPOSITORY}" | cut -d/ -f2)
          if [ -n "${CUSTOM_DOMAIN}" ]; then
            base="/"
          else
            base="/${repo}/"
          fi
          echo "Building with base: ${base}"
          npm run build --if-present -- --base "${base}"

      - name: Add CNAME if custom domain set
        if: env.CUSTOM_DOMAIN != ''
        run: |
          mkdir -p ./dist
          echo "${{ env.CUSTOM_DOMAIN }}" > ./dist/CNAME

      - name: Create SPA fallback (index -> 404)
        run: |
          if [ -d ./dist ] && [ -f ./dist/index.html ]; then
            cp ./dist/index.html ./dist/404.html
          fi

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # ensure commits have a clear identity
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
          # allow empty commits so the action won't fail if nothing changed
          allow_empty_commit: true
          # optional: customise commit message (will show in gh-pages commits)
          commit_message: "Deploy to gh-pages: ${{ github.sha }}"
